#!/bin/bash

# enable nbserverproxy
jupyter serverextension enable --sys-prefix nbserverproxy

# install the flask server extension so that
# flask launches at startup
mv runserver.py ${NB_PYTHON_PREFIX}/lib/python*/site-packages/

# enable bokeh extension
jupyter serverextension enable --sys-prefix runserver